### ISSUE TITLE
Update 1.0.13 will not load when using AzuEPI

### ISSUE THREAD

**Issue by Toriansel** [shudnal/HipLantern#2]
When loaded with AzuEPI version 1.0.13 gives the following error. I assume removing the ExtraSlots API broke compatibly with other supported alternate inventory mods. The same is true for CircletExtended.

[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'ExtraSlots, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by source-guilherme** [comment]
+1 with AzuEPI.

**Comment by shudnal** [comment]
Fixed in 1.0.14
